import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SolWalletProvider from "@/providers/SolWalletProvider";
import "@solana/wallet-adapter-react-ui/styles.css";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/providers/AppProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plats app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const cookieStore = cookies()
  const accessToken = cookieStore.get('accessToken')
  let user:  any | null = null;

  return (
    <html lang="en">
      <body className={inter.className}>
        <SolWalletProvider>
          <AppProvider initialAccessToken={accessToken?.value} user={user}>
          <Toaster />
          <div className="bg-[url('/background.jpg')] bg-no-repeat bg-cover bg-center">
          {children}
          </div>
        
          </AppProvider>
       </SolWalletProvider>
      </body>
    </html>
  );
}
