import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/providers/AppProvider";
import { cookies } from "next/headers";
import { AptosProvider } from "@/providers/AptosContext";
import SuiWalletProvider from "@/providers/SuiWalletProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plats app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const cookieStore = cookies()
  const accessToken = cookieStore.get('accessToken')
  let user:  any | null = null;

  return (
    <html lang="en">
      <body className={inter.className}>
      <AptosProvider>
        <SuiWalletProvider
       
        >
        <AppProvider initialAccessToken={accessToken?.value} user={user}>
          <Toaster />
          <div className="bg-[url('/background.jpg')] bg-no-repeat bg-cover bg-center">
          {children}
          </div>
        
          </AppProvider>
        </SuiWalletProvider>

      </AptosProvider>
         
      
      </body>
    </html>
  );
}
