build-layer:
	rm -rf ./layer
	mkdir layer
	mkdir layer/python
	mkdir layer/python/lib
	mkdir layer/python/lib/python3.11
	mkdir layer/python/lib/python3.11/site-packages
	pip install --target ./layer/python/lib/python3.11/site-packages -r requirements.txt